# Generated by Django 5.2 on 2025-04-10 22:07

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to=courses.models.handle_upload)),
                ("publish_date", models.DateField()),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("any", "Anyone"),
                            ("email_required", "Email required"),
                        ],
                        default="any",
                        max_length=25,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pub", "Published"),
                            ("soon", "Coming Soon"),
                            ("draft", "Draft"),
                        ],
                        default="draft",
                        max_length=5,
                    ),
                ),
            ],
        ),
    ]
